//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Services.Repository.ygfxpsvi
{

	[Persistent(@"mpp.account")]
	public partial class AccountEntity : XPLiteObject
	{
		int fId;
		[Key(true)]
		[Persistent(@"id")]
		[ColumnDbDefaultValue("nextval('mpp.user_id_seq'::regclass)")]
		public int Id
		{
			get { return fId; }
			set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
		}
		string fUsername;
		[Indexed(Name = @"user_username_uindex", Unique = true)]
		[Size(SizeAttribute.Unlimited)]
		[Persistent(@"username")]
		public string Username
		{
			get { return fUsername; }
			set { SetPropertyValue<string>(nameof(Username), ref fUsername, value); }
		}
		string fPassword;
		[Size(SizeAttribute.Unlimited)]
		[Persistent(@"password")]
		public string Password
		{
			get { return fPassword; }
			set { SetPropertyValue<string>(nameof(Password), ref fPassword, value); }
		}
	}

}
