//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Services.Repository.ygfxpsvi
{

	[Persistent(@"mpp.destination")]
	public partial class DestinationEntity : XPLiteObject
	{
		int fId;
		[Key(true)]
		[Persistent(@"id")]
		[ColumnDbDefaultValue("nextval('mpp.destination_id_seq'::regclass)")]
		public int Id
		{
			get { return fId; }
			set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
		}
		string fName;
		[Size(SizeAttribute.Unlimited)]
		[Persistent(@"name")]
		public string Name
		{
			get { return fName; }
			set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
		}
		[Association(@"TripEntityReferencesDestinationEntity")]
		public XPCollection<TripEntity> Trips { get { return GetCollection<TripEntity>(nameof(Trips)); } }
	}

}
