//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Services.Repository.ygfxpsvi
{

	[Persistent(@"mpp.reservation")]
	public partial class ReservationEntity : XPLiteObject
	{
		int fId;
		[Key(true)]
		[Persistent(@"id")]
		[ColumnDbDefaultValue("nextval('mpp.reservation_id_seq'::regclass)")]
		public int Id
		{
			get { return fId; }
			set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
		}
		string fClient_name;
		[Size(SizeAttribute.Unlimited)]
		[Persistent(@"client_name")]
		public string Client_name
		{
			get { return fClient_name; }
			set { SetPropertyValue<string>(nameof(Client_name), ref fClient_name, value); }
		}
		int fSeats_nr;
		[Persistent(@"seats_nr")]
		public int Seats_nr
		{
			get { return fSeats_nr; }
			set { SetPropertyValue<int>(nameof(Seats_nr), ref fSeats_nr, value); }
		}
		TripEntity fTrip_id;
		[Persistent(@"trip_id")]
		[Association(@"ReservationEntityReferencesTripEntity")]
		public TripEntity Trip_id
		{
			get { return fTrip_id; }
			set { SetPropertyValue<TripEntity>(nameof(Trip_id), ref fTrip_id, value); }
		}
	}

}
