//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using Services.Repository.ygfxpsvi;
using Microsoft.Extensions.DependencyInjection;

namespace Services.Repository.ygfxpsvi
{
	public partial class ygfxpsviUnitOfWork : UnitOfWork
	{
		public ygfxpsviUnitOfWork() : base() { }
		public ygfxpsviUnitOfWork(DevExpress.Xpo.Metadata.XPDictionary dictionary) : base(dictionary) { }
		public ygfxpsviUnitOfWork(IDataLayer layer, params IDisposable[] disposeOnDisconnect) : base(layer, disposeOnDisconnect) { }
		public ygfxpsviUnitOfWork(IObjectLayer layer, params IDisposable[] disposeOnDisconnect) : base(layer, disposeOnDisconnect) { }
	}
}
namespace Microsoft.Extensions.DependencyInjection
{
	public static class ygfxpsviXpoServiceCollectionExtensions
	{
		public static IServiceCollection AddygfxpsviAsXpoDefaultUnitOfWork(this IServiceCollection serviceCollection, bool useDataLayerAsSingletone = true, Action<DataLayerOptionsBuilder> customDataLayerOptionsBuilder = null)
		{
			Action<DataLayerOptionsBuilder> optionsBuilder = CreateDataLayerOptionsBuilder(customDataLayerOptionsBuilder);
			return serviceCollection.AddXpoDefaultUnitOfWork(useDataLayerAsSingletone, optionsBuilder);
		}
		public static IServiceCollection AddygfxpsviAsXpoDefaultSession(this IServiceCollection serviceCollection, bool useDataLayerAsSingletone = true, Action<DataLayerOptionsBuilder> customDataLayerOptionsBuilder = null)
		{
			Action<DataLayerOptionsBuilder> optionsBuilder = CreateDataLayerOptionsBuilder(customDataLayerOptionsBuilder);
			return serviceCollection.AddXpoDefaultSession(useDataLayerAsSingletone, optionsBuilder);
		}
		public static IServiceCollection AddygfxpsviUnitOfWork(this IServiceCollection serviceCollection, bool useDataLayerAsSingletone = true, Action<DataLayerOptionsBuilder> customDataLayerOptionsBuilder = null)
		{
			Action<DataLayerOptionsBuilder> optionsBuilder = CreateDataLayerOptionsBuilder(customDataLayerOptionsBuilder);
			return serviceCollection.AddXpoCustomSession<ygfxpsviUnitOfWork>(useDataLayerAsSingletone, optionsBuilder);
		}
		public static IServiceCollection AddygfxpsviXpoDefaultDataLayer(this IServiceCollection serviceCollection, ServiceLifetime lifetime, Action<DataLayerOptionsBuilder> customDataLayerOptionsBuilder = null)
		{
			Action<DataLayerOptionsBuilder> optionsBuilder = CreateDataLayerOptionsBuilder(customDataLayerOptionsBuilder);
			return serviceCollection.AddXpoDefaultDataLayer(lifetime, customDataLayerOptionsBuilder);
		}
		static Action<DataLayerOptionsBuilder> CreateDataLayerOptionsBuilder(Action<DataLayerOptionsBuilder> injectCustomDataLayerOptionsBuilder)
		{
			return (options) =>
			{
				options
				.UseConnectionString(ConnectionHelper.ConnectionString)
				.UseEntityTypes(ConnectionHelper.GetPersistentTypes());
				if (injectCustomDataLayerOptionsBuilder != null)
				{
					injectCustomDataLayerOptionsBuilder(options);
				}
			};
		}
	}
}
