//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Services.Repository.ygfxpsvi
{

	[Persistent(@"mpp.trip")]
	public partial class TripEntity : XPLiteObject
	{
		int fId;
		[Key(true)]
		[Persistent(@"id")]
		[ColumnDbDefaultValue("nextval('mpp.trip_id_seq'::regclass)")]
		public int Id
		{
			get { return fId; }
			set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
		}
		DateTime fDeparture;
		[Persistent(@"departure")]
		public DateTime Departure
		{
			get { return fDeparture; }
			set { SetPropertyValue<DateTime>(nameof(Departure), ref fDeparture, value); }
		}
		DestinationEntity fDestination_id;
		[Persistent(@"destination_id")]
		[Association(@"TripEntityReferencesDestinationEntity")]
		public DestinationEntity Destination_id
		{
			get { return fDestination_id; }
			set { SetPropertyValue<DestinationEntity>(nameof(Destination_id), ref fDestination_id, value); }
		}
		[Association(@"ReservationEntityReferencesTripEntity")]
		public XPCollection<ReservationEntity> Reservations { get { return GetCollection<ReservationEntity>(nameof(Reservations)); } }
	}

}
